//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Modules.OrientalSails.Web.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portal.Modules.OrientalSails.Web.Admin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string btnDisplay {
            get {
                return ResourceManager.GetString("btnDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export customer data.
        /// </summary>
        internal static string btnExcel {
            get {
                return ResourceManager.GetString("btnExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export tour.
        /// </summary>
        internal static string btnExport {
            get {
                return ResourceManager.GetString("btnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export list.
        /// </summary>
        internal static string btnExportAgencyList {
            get {
                return ResourceManager.GetString("btnExportAgencyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to excel.
        /// </summary>
        internal static string btnExportExcel {
            get {
                return ResourceManager.GetString("btnExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export room list.
        /// </summary>
        internal static string btnExportRoom {
            get {
                return ResourceManager.GetString("btnExportRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Welcome board.
        /// </summary>
        internal static string btnExportWelcome {
            get {
                return ResourceManager.GetString("btnExportWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provisional Register.
        /// </summary>
        internal static string btnProvisional {
            get {
                return ResourceManager.GetString("btnProvisional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string btnRemove {
            get {
                return ResourceManager.GetString("btnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save without export.
        /// </summary>
        internal static string btnSaveExpenses {
            get {
                return ResourceManager.GetString("btnSaveExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string buttonAdd {
            get {
                return ResourceManager.GetString("buttonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string buttonCancel {
            get {
                return ResourceManager.GetString("buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string buttonSave {
            get {
                return ResourceManager.GetString("buttonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string buttonSearch {
            get {
                return ResourceManager.GetString("buttonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string buttonSubmit {
            get {
                return ResourceManager.GetString("buttonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has contact name and phone.
        /// </summary>
        internal static string chkIsCustomType {
            get {
                return ResourceManager.GetString("chkIsCustomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is daily.
        /// </summary>
        internal static string chkIsDaily {
            get {
                return ResourceManager.GetString("chkIsDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually input.
        /// </summary>
        internal static string chkIsDailyInput {
            get {
                return ResourceManager.GetString("chkIsDailyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is monthly.
        /// </summary>
        internal static string chkIsMonthly {
            get {
                return ResourceManager.GetString("chkIsMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is supplier.
        /// </summary>
        internal static string chkIsSupplier {
            get {
                return ResourceManager.GetString("chkIsSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is yearly.
        /// </summary>
        internal static string chkIsYearly {
            get {
                return ResourceManager.GetString("chkIsYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send notify.
        /// </summary>
        internal static string chkSendMail {
            get {
                return ResourceManager.GetString("chkSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some booking error in this period, please correct!.
        /// </summary>
        internal static string errorBookingPeriod {
            get {
                return ResourceManager.GetString("errorBookingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input booking value manually, pricing system is not valid.
        /// </summary>
        internal static string errorCanNotCalculatePrice {
            get {
                return ResourceManager.GetString("errorCanNotCalculatePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is required!.
        /// </summary>
        internal static string errorDateRequired {
            get {
                return ResourceManager.GetString("errorDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom booking code is duplicated! Please check this booking again..
        /// </summary>
        internal static string errorDuplicateBookingCode {
            get {
                return ResourceManager.GetString("errorDuplicateBookingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not save data when there is no passenger!.
        /// </summary>
        internal static string errorNoBookingExport {
            get {
                return ResourceManager.GetString("errorNoBookingExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not save data when there is no passenger!.
        /// </summary>
        internal static string errorNoBookingSave {
            get {
                return ResourceManager.GetString("errorNoBookingSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough room available!.
        /// </summary>
        internal static string errorNotEnoughAvailable {
            get {
                return ResourceManager.GetString("errorNotEnoughAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each room can contains only one child or baby.
        /// </summary>
        internal static string errorOneChildOneBaby {
            get {
                return ResourceManager.GetString("errorOneChildOneBaby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} baby(s).
        /// </summary>
        internal static string formatBabyItem {
            get {
                return ResourceManager.GetString("formatBabyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} child(s).
        /// </summary>
        internal static string formatChildItem {
            get {
                return ResourceManager.GetString("formatChildItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} adult, {1} child, {2} baby.
        /// </summary>
        internal static string formatCustomerCount {
            get {
                return ResourceManager.GetString("formatCustomerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult: {0}&lt;br/&gt;Child: {1} &lt;br/&gt;Baby: {2}.
        /// </summary>
        internal static string formatPaxDetail {
            get {
                return ResourceManager.GetString("formatPaxDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} person(s).
        /// </summary>
        internal static string formatPersonItem {
            get {
                return ResourceManager.GetString("formatPersonItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} room(s).
        /// </summary>
        internal static string formatRoomItem {
            get {
                return ResourceManager.GetString("formatRoomItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add booking.
        /// </summary>
        internal static string hplAddBooking {
            get {
                return ResourceManager.GetString("hplAddBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new partner.
        /// </summary>
        internal static string hplAgencyEdit {
            get {
                return ResourceManager.GetString("hplAgencyEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners manager.
        /// </summary>
        internal static string hplAgencyList {
            get {
                return ResourceManager.GetString("hplAgencyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string hplBalance {
            get {
                return ResourceManager.GetString("hplBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking by date.
        /// </summary>
        internal static string hplBookingDate {
            get {
                return ResourceManager.GetString("hplBookingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking by period.
        /// </summary>
        internal static string hplBookingPeriod {
            get {
                return ResourceManager.GetString("hplBookingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer expenses.
        /// </summary>
        internal static string hplCosting {
            get {
                return ResourceManager.GetString("hplCosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense types configuration.
        /// </summary>
        internal static string hplCostTypes {
            get {
                return ResourceManager.GetString("hplCostTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new cruise.
        /// </summary>
        internal static string hplCruiseEdit {
            get {
                return ResourceManager.GetString("hplCruiseEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cruise manager.
        /// </summary>
        internal static string hplCruiseList {
            get {
                return ResourceManager.GetString("hplCruiseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running expenses.
        /// </summary>
        internal static string hplDailyCost {
            get {
                return ResourceManager.GetString("hplDailyCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily expenses.
        /// </summary>
        internal static string hplExpenseDate {
            get {
                return ResourceManager.GetString("hplExpenseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payables.
        /// </summary>
        internal static string hplExpenseDebt {
            get {
                return ResourceManager.GetString("hplExpenseDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly/Yearly expenses.
        /// </summary>
        internal static string hplExpensePeriod {
            get {
                return ResourceManager.GetString("hplExpensePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense report.
        /// </summary>
        internal static string hplExpenseReport {
            get {
                return ResourceManager.GetString("hplExpenseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed expenses.
        /// </summary>
        internal static string hplHaiPhong {
            get {
                return ResourceManager.GetString("hplHaiPhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string hplHome {
            get {
                return ResourceManager.GetString("hplHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receivables.
        /// </summary>
        internal static string hplIncomeOwn {
            get {
                return ResourceManager.GetString("hplIncomeOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        internal static string hplIncomeReport {
            get {
                return ResourceManager.GetString("hplIncomeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order manager.
        /// </summary>
        internal static string hplOrders {
            get {
                return ResourceManager.GetString("hplOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking changed by date.
        /// </summary>
        internal static string hplRevenueChanged {
            get {
                return ResourceManager.GetString("hplRevenueChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD to VND rates.
        /// </summary>
        internal static string hplUSDRate {
            get {
                return ResourceManager.GetString("hplUSDRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner price policy.
        /// </summary>
        internal static string hyperLinkAgencyList {
            get {
                return ResourceManager.GetString("hyperLinkAgencyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking manager.
        /// </summary>
        internal static string hyperLinkBookingList {
            get {
                return ResourceManager.GetString("hyperLinkBookingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra option manager.
        /// </summary>
        internal static string hyperLinkExtraOption {
            get {
                return ResourceManager.GetString("hyperLinkExtraOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room classes manager.
        /// </summary>
        internal static string hyperLinkRoomClass {
            get {
                return ResourceManager.GetString("hyperLinkRoomClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new room.
        /// </summary>
        internal static string hyperLinkRoomEdit {
            get {
                return ResourceManager.GetString("hyperLinkRoomEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms managers.
        /// </summary>
        internal static string hyperLinkRoomList {
            get {
                return ResourceManager.GetString("hyperLinkRoomList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room types manager.
        /// </summary>
        internal static string hyperLinkRoomType {
            get {
                return ResourceManager.GetString("hyperLinkRoomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new trip.
        /// </summary>
        internal static string hyperLinkTripEdit {
            get {
                return ResourceManager.GetString("hyperLinkTripEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip config.
        /// </summary>
        internal static string hyperLinkTripList {
            get {
                return ResourceManager.GetString("hyperLinkTripList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Include {
            get {
                return ResourceManager.GetString("Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string labelAction {
            get {
                return ResourceManager.GetString("labelAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string labelActivities {
            get {
                return ResourceManager.GetString("labelActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Id.
        /// </summary>
        internal static string labelBookingId {
            get {
                return ResourceManager.GetString("labelBookingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        internal static string labelCapacity {
            get {
                return ResourceManager.GetString("labelCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string labelCustomer {
            get {
                return ResourceManager.GetString("labelCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers List.
        /// </summary>
        internal static string labelCustomerList {
            get {
                return ResourceManager.GetString("labelCustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string labelDescription {
            get {
                return ResourceManager.GetString("labelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusions.
        /// </summary>
        internal static string labelExclusions {
            get {
                return ResourceManager.GetString("labelExclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclusions.
        /// </summary>
        internal static string labelInclusions {
            get {
                return ResourceManager.GetString("labelInclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Transfer.
        /// </summary>
        internal static string labelIsTransfer {
            get {
                return ResourceManager.GetString("labelIsTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string labelName {
            get {
                return ResourceManager.GetString("labelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of day.
        /// </summary>
        internal static string labelNumberOfDay {
            get {
                return ResourceManager.GetString("labelNumberOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of option.
        /// </summary>
        internal static string labelNumberOfOptions {
            get {
                return ResourceManager.GetString("labelNumberOfOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        internal static string labelPartner {
            get {
                return ResourceManager.GetString("labelPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string labelPrice {
            get {
                return ResourceManager.GetString("labelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string labelRole {
            get {
                return ResourceManager.GetString("labelRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Class.
        /// </summary>
        internal static string labelRoomClass {
            get {
                return ResourceManager.GetString("labelRoomClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room List.
        /// </summary>
        internal static string labelRoomList {
            get {
                return ResourceManager.GetString("labelRoomList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room types management.
        /// </summary>
        internal static string labelRoomTypes {
            get {
                return ResourceManager.GetString("labelRoomTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Type.
        /// </summary>
        internal static string labelRoomTypex {
            get {
                return ResourceManager.GetString("labelRoomTypex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        internal static string labelSale {
            get {
                return ResourceManager.GetString("labelSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email.
        /// </summary>
        internal static string labelSendEmail {
            get {
                return ResourceManager.GetString("labelSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string labelStartDate {
            get {
                return ResourceManager.GetString("labelStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string labelStatus {
            get {
                return ResourceManager.GetString("labelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abtract Image (150 x XX).
        /// </summary>
        internal static string labelTripImage {
            get {
                return ResourceManager.GetString("labelTripImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map ( 235x170).
        /// </summary>
        internal static string labelTripMap {
            get {
                return ResourceManager.GetString("labelTripMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip.
        /// </summary>
        internal static string labelTripName {
            get {
                return ResourceManager.GetString("labelTripName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to take.
        /// </summary>
        internal static string labelWhatToTake {
            get {
                return ResourceManager.GetString("labelWhatToTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Calculate].
        /// </summary>
        internal static string lbtCalculate {
            get {
                return ResourceManager.GetString("lbtCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Check avaiable].
        /// </summary>
        internal static string lbtCheckAvaiable {
            get {
                return ResourceManager.GetString("lbtCheckAvaiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string messageConfirmDelete {
            get {
                return ResourceManager.GetString("messageConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: You may have input wrong data. Can not apply for the value between {0} and {1}. There is no range to apply..
        /// </summary>
        internal static string messageErrorDontHaveRangeFor {
            get {
                return ResourceManager.GetString("messageErrorDontHaveRangeFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: You may have input wrong data. Can not apply for the value between {1} and {0}. There is two range to apply..
        /// </summary>
        internal static string messageErrorOneValueBelongToTwoRange {
            get {
                return ResourceManager.GetString("messageErrorOneValueBelongToTwoRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: You may have input wrong data. There is two range without max value..
        /// </summary>
        internal static string messageErrorTwoMaxValue {
            get {
                return ResourceManager.GetString("messageErrorTwoMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oop! You don&apos;t have permission..
        /// </summary>
        internal static string stringAccessDenied {
            get {
                return ResourceManager.GetString("stringAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new option.
        /// </summary>
        internal static string stringAddnewExtraOption {
            get {
                return ResourceManager.GetString("stringAddnewExtraOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new room class.
        /// </summary>
        internal static string stringAddnewRoomClass {
            get {
                return ResourceManager.GetString("stringAddnewRoomClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total users: {0}.
        /// </summary>
        internal static string stringFormatUserCount {
            get {
                return ResourceManager.GetString("stringFormatUserCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        internal static string stringGuest {
            get {
                return ResourceManager.GetString("stringGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookings.
        /// </summary>
        internal static string tabBooking {
            get {
                return ResourceManager.GetString("tabBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        internal static string tabConfiguration {
            get {
                return ResourceManager.GetString("tabConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost configuration.
        /// </summary>
        internal static string tabCost {
            get {
                return ResourceManager.GetString("tabCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string tabCustomers {
            get {
                return ResourceManager.GetString("tabCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string tabReports {
            get {
                return ResourceManager.GetString("tabReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room manager.
        /// </summary>
        internal static string tabRoom {
            get {
                return ResourceManager.GetString("tabRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string tabSetting {
            get {
                return ResourceManager.GetString("tabSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cruises &amp; trips.
        /// </summary>
        internal static string tabTrips {
            get {
                return ResourceManager.GetString("tabTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountant.
        /// </summary>
        internal static string textAccountant {
            get {
                return ResourceManager.GetString("textAccountant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        internal static string textAccounting {
            get {
                return ResourceManager.GetString("textAccounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not updated.
        /// </summary>
        internal static string textAccountingModified {
            get {
                return ResourceManager.GetString("textAccountingModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New booking.
        /// </summary>
        internal static string textAccountingNew {
            get {
                return ResourceManager.GetString("textAccountingNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting status.
        /// </summary>
        internal static string textAccountingStatus {
            get {
                return ResourceManager.GetString("textAccountingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string textAccountingUpdated {
            get {
                return ResourceManager.GetString("textAccountingUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add booking.
        /// </summary>
        internal static string textAddBooking {
            get {
                return ResourceManager.GetString("textAddBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string textAddress {
            get {
                return ResourceManager.GetString("textAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        internal static string textAdult {
            get {
                return ResourceManager.GetString("textAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult cost.
        /// </summary>
        internal static string textAdultCost {
            get {
                return ResourceManager.GetString("textAdultCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency.
        /// </summary>
        internal static string textAgency {
            get {
                return ResourceManager.GetString("textAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TA Code.
        /// </summary>
        internal static string textAgencyCode {
            get {
                return ResourceManager.GetString("textAgencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency information.
        /// </summary>
        internal static string textAgencyEdit {
            get {
                return ResourceManager.GetString("textAgencyEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency name.
        /// </summary>
        internal static string textAgencyName {
            get {
                return ResourceManager.GetString("textAgencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow booking with diffirent people.
        /// </summary>
        internal static string textAllowSingleBooking {
            get {
                return ResourceManager.GetString("textAllowSingleBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And go on.
        /// </summary>
        internal static string textAndUp {
            get {
                return ResourceManager.GetString("textAndUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved by.
        /// </summary>
        internal static string textApprovedBy {
            get {
                return ResourceManager.GetString("textApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned user.
        /// </summary>
        internal static string textAssignedUser {
            get {
                return ResourceManager.GetString("textAssignedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby.
        /// </summary>
        internal static string textBaby {
            get {
                return ResourceManager.GetString("textBaby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby cost.
        /// </summary>
        internal static string textBabyCost {
            get {
                return ResourceManager.GetString("textBabyCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        internal static string textBirthDate {
            get {
                return ResourceManager.GetString("textBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booker.
        /// </summary>
        internal static string textBooker {
            get {
                return ResourceManager.GetString("textBooker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking by date.
        /// </summary>
        internal static string textBookingByDate {
            get {
                return ResourceManager.GetString("textBookingByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking by period.
        /// </summary>
        internal static string textBookingByPeriod {
            get {
                return ResourceManager.GetString("textBookingByPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking charter.
        /// </summary>
        internal static string textBookingCharter {
            get {
                return ResourceManager.GetString("textBookingCharter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking code.
        /// </summary>
        internal static string textBookingCode {
            get {
                return ResourceManager.GetString("textBookingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking code format.
        /// </summary>
        internal static string textBookingCodeFormat {
            get {
                return ResourceManager.GetString("textBookingCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created date.
        /// </summary>
        internal static string textBookingDate {
            get {
                return ResourceManager.GetString("textBookingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking list.
        /// </summary>
        internal static string textBookingList {
            get {
                return ResourceManager.GetString("textBookingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking type.
        /// </summary>
        internal static string textBookingType {
            get {
                return ResourceManager.GetString("textBookingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed content.
        /// </summary>
        internal static string textChangedContent {
            get {
                return ResourceManager.GetString("textChangedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed time.
        /// </summary>
        internal static string textChangedTime {
            get {
                return ResourceManager.GetString("textChangedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed revenue.
        /// </summary>
        internal static string textChangedTotal {
            get {
                return ResourceManager.GetString("textChangedTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in pax.
        /// </summary>
        internal static string textCheckInPax {
            get {
                return ResourceManager.GetString("textCheckInPax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        internal static string textChild {
            get {
                return ResourceManager.GetString("textChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child cost.
        /// </summary>
        internal static string textChildCost {
            get {
                return ResourceManager.GetString("textChildCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child price percentage.
        /// </summary>
        internal static string textChildPercentage {
            get {
                return ResourceManager.GetString("textChildPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm by.
        /// </summary>
        internal static string textConfirmBy {
            get {
                return ResourceManager.GetString("textConfirmBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        internal static string textContract {
            get {
                return ResourceManager.GetString("textContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract name.
        /// </summary>
        internal static string textContractName {
            get {
                return ResourceManager.GetString("textContractName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract status.
        /// </summary>
        internal static string textContractStatus {
            get {
                return ResourceManager.GetString("textContractStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload contract.
        /// </summary>
        internal static string textContractUpload {
            get {
                return ResourceManager.GetString("textContractUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string textCost {
            get {
                return ResourceManager.GetString("textCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costing configuration.
        /// </summary>
        internal static string textCostingConfiguration {
            get {
                return ResourceManager.GetString("textCostingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Type.
        /// </summary>
        internal static string textCostType {
            get {
                return ResourceManager.GetString("textCostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string textCreated {
            get {
                return ResourceManager.GetString("textCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cruise.
        /// </summary>
        internal static string textCruise {
            get {
                return ResourceManager.GetString("textCruise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer info.
        /// </summary>
        internal static string textCustomerInfo {
            get {
                return ResourceManager.GetString("textCustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer list.
        /// </summary>
        internal static string textCustomerList {
            get {
                return ResourceManager.GetString("textCustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name.
        /// </summary>
        internal static string textCustomerName {
            get {
                return ResourceManager.GetString("textCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string textDate {
            get {
                return ResourceManager.GetString("textDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date.
        /// </summary>
        internal static string textDateFrom {
            get {
                return ResourceManager.GetString("textDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date.
        /// </summary>
        internal static string textDateTo {
            get {
                return ResourceManager.GetString("textDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date to view.
        /// </summary>
        internal static string textDateToView {
            get {
                return ResourceManager.GetString("textDateToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to use this function!.
        /// </summary>
        internal static string textDeniedFunction {
            get {
                return ResourceManager.GetString("textDeniedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string textEmail {
            get {
                return ResourceManager.GetString("textEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate (1 USD to VND).
        /// </summary>
        internal static string textExchangeRate {
            get {
                return ResourceManager.GetString("textExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense partner ship manager.
        /// </summary>
        internal static string textExpensePartnershipManager {
            get {
                return ResourceManager.GetString("textExpensePartnershipManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired date.
        /// </summary>
        internal static string textExpiredDate {
            get {
                return ResourceManager.GetString("textExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To config this service as an expense (if not already), &lt;a href=&apos;{0}&apos;&gt;click here&lt;a&gt; and add a service with associated services is this service.
        /// </summary>
        internal static string textExtraNote {
            get {
                return ResourceManager.GetString("textExtraNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra services.
        /// </summary>
        internal static string textExtraService {
            get {
                return ResourceManager.GetString("textExtraService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string textFax {
            get {
                return ResourceManager.GetString("textFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string textFrom {
            get {
                return ResourceManager.GetString("textFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string textFullName {
            get {
                return ResourceManager.GetString("textFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string textGender {
            get {
                return ResourceManager.GetString("textGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General information.
        /// </summary>
        internal static string textGeneralInformation {
            get {
                return ResourceManager.GetString("textGeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRAND TOTAL.
        /// </summary>
        internal static string textGrandTotal {
            get {
                return ResourceManager.GetString("textGrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include.
        /// </summary>
        internal static string textInclude {
            get {
                return ResourceManager.GetString("textInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is included in room price.
        /// </summary>
        internal static string textIncludedInRoomPrice {
            get {
                return ResourceManager.GetString("textIncludedInRoomPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string textIndex {
            get {
                return ResourceManager.GetString("textIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is shared cabin.
        /// </summary>
        internal static string textIsShared {
            get {
                return ResourceManager.GetString("textIsShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is transferred.
        /// </summary>
        internal static string textIsTransferred {
            get {
                return ResourceManager.GetString("textIsTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last booking.
        /// </summary>
        internal static string textLastBooking {
            get {
                return ResourceManager.GetString("textLastBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        internal static string textLock {
            get {
                return ResourceManager.GetString("textLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed user.
        /// </summary>
        internal static string textModifiedBy {
            get {
                return ResourceManager.GetString("textModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string textName {
            get {
                return ResourceManager.GetString("textName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string textNationality {
            get {
                return ResourceManager.GetString("textNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New room class.
        /// </summary>
        internal static string textNewRoomClass {
            get {
                return ResourceManager.GetString("textNewRoomClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New room type.
        /// </summary>
        internal static string textNewRoomType {
            get {
                return ResourceManager.GetString("textNewRoomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string textNote {
            get {
                return ResourceManager.GetString("textNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify.
        /// </summary>
        internal static string textNotify {
            get {
                return ResourceManager.GetString("textNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of cabin.
        /// </summary>
        internal static string textNumberOfCabin {
            get {
                return ResourceManager.GetString("textNumberOfCabin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pax.
        /// </summary>
        internal static string textNumberOfPax {
            get {
                return ResourceManager.GetString("textNumberOfPax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        internal static string textOption {
            get {
                return ResourceManager.GetString("textOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order waiting.
        /// </summary>
        internal static string textOrderReport {
            get {
                return ResourceManager.GetString("textOrderReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other info.
        /// </summary>
        internal static string textOthers {
            get {
                return ResourceManager.GetString("textOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport.
        /// </summary>
        internal static string textPassport {
            get {
                return ResourceManager.GetString("textPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of pax.
        /// </summary>
        internal static string textPax {
            get {
                return ResourceManager.GetString("textPax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay before tour.
        /// </summary>
        internal static string textPaymentNeeded {
            get {
                return ResourceManager.GetString("textPaymentNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Period.
        /// </summary>
        internal static string textPaymentPeriod {
            get {
                return ResourceManager.GetString("textPaymentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string textPhone {
            get {
                return ResourceManager.GetString("textPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup Address.
        /// </summary>
        internal static string textPickupAddress {
            get {
                return ResourceManager.GetString("textPickupAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string textPriceConfig {
            get {
                return ResourceManager.GetString("textPriceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport detail.
        /// </summary>
        internal static string textProvisionalDetail {
            get {
                return ResourceManager.GetString("textProvisionalDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        internal static string textPurpose {
            get {
                return ResourceManager.GetString("textPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string textRole {
            get {
                return ResourceManager.GetString("textRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string textRoom {
            get {
                return ResourceManager.GetString("textRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room number.
        /// </summary>
        internal static string textRoomNumber {
            get {
                return ResourceManager.GetString("textRoomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        internal static string textSale {
            get {
                return ResourceManager.GetString("textSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale in charge.
        /// </summary>
        internal static string textSaleInCharge {
            get {
                return ResourceManager.GetString("textSaleInCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Agency --.
        /// </summary>
        internal static string textSelectAgency {
            get {
                return ResourceManager.GetString("textSelectAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to not updated.
        /// </summary>
        internal static string textSetAsNotUpdated {
            get {
                return ResourceManager.GetString("textSetAsNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to updated.
        /// </summary>
        internal static string textSetAsUpdated {
            get {
                return ResourceManager.GetString("textSetAsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show customer name.
        /// </summary>
        internal static string textShowCustomerName {
            get {
                return ResourceManager.GetString("textShowCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This form will show all customers onboard (include customers who stayed from the day before in more than 2 day trips) in a specific day.
        /// </summary>
        internal static string textShowCustomerOnboardNote {
            get {
                return ResourceManager.GetString("textShowCustomerOnboardNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer who was transfered from the day before will display in yellow background.
        /// </summary>
        internal static string textShowCustomerTransferNote {
            get {
                return ResourceManager.GetString("textShowCustomerTransferNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special request.
        /// </summary>
        internal static string textSpecialRequest {
            get {
                return ResourceManager.GetString("textSpecialRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string textStartDate {
            get {
                return ResourceManager.GetString("textStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking status.
        /// </summary>
        internal static string textStatus {
            get {
                return ResourceManager.GetString("textStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string textStatusAll {
            get {
                return ResourceManager.GetString("textStatusAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Approve].
        /// </summary>
        internal static string textStatusApprove {
            get {
                return ResourceManager.GetString("textStatusApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string textStatusApproved {
            get {
                return ResourceManager.GetString("textStatusApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Not enough room].
        /// </summary>
        internal static string textStatusNotAvaiable {
            get {
                return ResourceManager.GetString("textStatusNotAvaiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string textStatusPending {
            get {
                return ResourceManager.GetString("textStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Reject].
        /// </summary>
        internal static string textStatusReject {
            get {
                return ResourceManager.GetString("textStatusReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string textStatusRejected {
            get {
                return ResourceManager.GetString("textStatusRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay from.
        /// </summary>
        internal static string textStayFrom {
            get {
                return ResourceManager.GetString("textStayFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay in.
        /// </summary>
        internal static string textStayIn {
            get {
                return ResourceManager.GetString("textStayIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay term.
        /// </summary>
        internal static string textStayTerm {
            get {
                return ResourceManager.GetString("textStayTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay to.
        /// </summary>
        internal static string textStayTo {
            get {
                return ResourceManager.GetString("textStayTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string textSupplier {
            get {
                return ResourceManager.GetString("textSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply for.
        /// </summary>
        internal static string textTargetApply {
            get {
                return ResourceManager.GetString("textTargetApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax code.
        /// </summary>
        internal static string textTaxCode {
            get {
                return ResourceManager.GetString("textTaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string textTo {
            get {
                return ResourceManager.GetString("textTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string textTotal {
            get {
                return ResourceManager.GetString("textTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string textTotalPax {
            get {
                return ResourceManager.GetString("textTotalPax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking report.
        /// </summary>
        internal static string textTrackingReport {
            get {
                return ResourceManager.GetString("textTrackingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        internal static string textTransferAdult {
            get {
                return ResourceManager.GetString("textTransferAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby.
        /// </summary>
        internal static string textTransferBaby {
            get {
                return ResourceManager.GetString("textTransferBaby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        internal static string textTransferChildren {
            get {
                return ResourceManager.GetString("textTransferChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred cost.
        /// </summary>
        internal static string textTransferredCost {
            get {
                return ResourceManager.GetString("textTransferredCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to.
        /// </summary>
        internal static string textTransferTo {
            get {
                return ResourceManager.GetString("textTransferTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip.
        /// </summary>
        internal static string textTrip {
            get {
                return ResourceManager.GetString("textTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip code.
        /// </summary>
        internal static string textTripCode {
            get {
                return ResourceManager.GetString("textTripCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string textUnknownNationality {
            get {
                return ResourceManager.GetString("textUnknownNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        internal static string textUnlock {
            get {
                return ResourceManager.GetString("textUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved.
        /// </summary>
        internal static string textUnsaved {
            get {
                return ResourceManager.GetString("textUnsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom booking code.
        /// </summary>
        internal static string textUseCustomBookingId {
            get {
                return ResourceManager.GetString("textUseCustomBookingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom price for each room.
        /// </summary>
        internal static string textUseCustomPriceForEachRoom {
            get {
                return ResourceManager.GetString("textUseCustomPriceForEachRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom price when add booking.
        /// </summary>
        internal static string textUseCustomPriceWhenAddBooking {
            get {
                return ResourceManager.GetString("textUseCustomPriceWhenAddBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user(s).
        /// </summary>
        internal static string textUser {
            get {
                return ResourceManager.GetString("textUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid from.
        /// </summary>
        internal static string textValidFrom {
            get {
                return ResourceManager.GetString("textValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viet Kieu.
        /// </summary>
        internal static string textVietKieu {
            get {
                return ResourceManager.GetString("textVietKieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa expired.
        /// </summary>
        internal static string textVisaExpired {
            get {
                return ResourceManager.GetString("textVisaExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa No..
        /// </summary>
        internal static string textVisaNo {
            get {
                return ResourceManager.GetString("textVisaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This pricing table will be apply for {0}.
        /// </summary>
        internal static string titleAdminAgencyEdit {
            get {
                return ResourceManager.GetString("titleAdminAgencyEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of users in role {0}.
        /// </summary>
        internal static string titleAdminAgencyUserList {
            get {
                return ResourceManager.GetString("titleAdminAgencyUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency List.
        /// </summary>
        internal static string titleAdminAgentList {
            get {
                return ResourceManager.GetString("titleAdminAgentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency list.
        /// </summary>
        internal static string titleAgencyList {
            get {
                return ResourceManager.GetString("titleAgencyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking List.
        /// </summary>
        internal static string titleBookingList {
            get {
                return ResourceManager.GetString("titleBookingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking by period.
        /// </summary>
        internal static string titleBookingPeriod {
            get {
                return ResourceManager.GetString("titleBookingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking View.
        /// </summary>
        internal static string titleBookingView {
            get {
                return ResourceManager.GetString("titleBookingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost types.
        /// </summary>
        internal static string titleCostType {
            get {
                return ResourceManager.GetString("titleCostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange rates.
        /// </summary>
        internal static string titleExchangeRate {
            get {
                return ResourceManager.GetString("titleExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Option.
        /// </summary>
        internal static string titleExtraOptionEdit {
            get {
                return ResourceManager.GetString("titleExtraOptionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income report.
        /// </summary>
        internal static string titleIncomeReport {
            get {
                return ResourceManager.GetString("titleIncomeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order report.
        /// </summary>
        internal static string titleOrderReport {
            get {
                return ResourceManager.GetString("titleOrderReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Class Edit.
        /// </summary>
        internal static string titleRoomClassEdit {
            get {
                return ResourceManager.GetString("titleRoomClassEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Edit.
        /// </summary>
        internal static string titleRoomEdit {
            get {
                return ResourceManager.GetString("titleRoomEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room List.
        /// </summary>
        internal static string titleRoomList {
            get {
                return ResourceManager.GetString("titleRoomList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sails Price Config.
        /// </summary>
        internal static string titleSailsPriceConfig {
            get {
                return ResourceManager.GetString("titleSailsPriceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Edit.
        /// </summary>
        internal static string titleSailsTripEdit {
            get {
                return ResourceManager.GetString("titleSailsTripEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip List.
        /// </summary>
        internal static string titleSailsTripList {
            get {
                return ResourceManager.GetString("titleSailsTripList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string titleSettings {
            get {
                return ResourceManager.GetString("titleSettings", resourceCulture);
            }
        }
    }
}
