//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Modules.TourManagement.Web.Controls {
    
    public partial class LocationTree {
        protected System.Web.UI.UpdatePanel UpdatePanel1;
        protected System.Web.UI.WebControls.TreeView treeViewLocation;
    }
}
