//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Modules.TourManagement.Web.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.Modules.TourManagement.Web.Admin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string btnAddAlbum {
            get {
                return ResourceManager.GetString("btnAddAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        internal static string btnAddNew {
            get {
                return ResourceManager.GetString("btnAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New region.
        /// </summary>
        internal static string btnAddNewRegion {
            get {
                return ResourceManager.GetString("btnAddNewRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string btnAddPrice {
            get {
                return ResourceManager.GetString("btnAddPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string btnChooseAlbum {
            get {
                return ResourceManager.GetString("btnChooseAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export details.
        /// </summary>
        internal static string btnExport {
            get {
                return ResourceManager.GetString("btnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string btnRemove {
            get {
                return ResourceManager.GetString("btnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string butonSearch {
            get {
                return ResourceManager.GetString("butonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat.
        /// </summary>
        internal static string buttonBoatConfig {
            get {
                return ResourceManager.GetString("buttonBoatConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string buttonCancel {
            get {
                return ResourceManager.GetString("buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        internal static string buttonHotelConfig {
            get {
                return ResourceManager.GetString("buttonHotelConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrance Fee.
        /// </summary>
        internal static string buttonLandscapeConfig {
            get {
                return ResourceManager.GetString("buttonLandscapeConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string buttonOverview {
            get {
                return ResourceManager.GetString("buttonOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        internal static string buttonRestaurantConfig {
            get {
                return ResourceManager.GetString("buttonRestaurantConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string buttonSearch {
            get {
                return ResourceManager.GetString("buttonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string buttonSubmit {
            get {
                return ResourceManager.GetString("buttonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        internal static string buttonTransportConfig {
            get {
                return ResourceManager.GetString("buttonTransportConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Choose City --.
        /// </summary>
        internal static string ChooseCity {
            get {
                return ResourceManager.GetString("ChooseCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Choose Country --.
        /// </summary>
        internal static string ChooseCountry {
            get {
                return ResourceManager.GetString("ChooseCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Choose District --.
        /// </summary>
        internal static string ChooseDistrict {
            get {
                return ResourceManager.GetString("ChooseDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Choose Region --.
        /// </summary>
        internal static string ChooseRegion {
            get {
                return ResourceManager.GetString("ChooseRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select region --.
        /// </summary>
        internal static string dropdownItemChooseArea {
            get {
                return ResourceManager.GetString("dropdownItemChooseArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select city --.
        /// </summary>
        internal static string dropdownItemChooseCity {
            get {
                return ResourceManager.GetString("dropdownItemChooseCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select country --.
        /// </summary>
        internal static string dropdownItemChooseCountry {
            get {
                return ResourceManager.GetString("dropdownItemChooseCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select district --.
        /// </summary>
        internal static string dropdownItemChooseDistrict {
            get {
                return ResourceManager.GetString("dropdownItemChooseDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange rates.
        /// </summary>
        internal static string hplCurrencies {
            get {
                return ResourceManager.GetString("hplCurrencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string hplEdit {
            get {
                return ResourceManager.GetString("hplEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin comments.
        /// </summary>
        internal static string hplLandscapeComment {
            get {
                return ResourceManager.GetString("hplLandscapeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin orders.
        /// </summary>
        internal static string hplRestaurantOrders {
            get {
                return ResourceManager.GetString("hplRestaurantOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string hplView {
            get {
                return ResourceManager.GetString("hplView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add guide rates.
        /// </summary>
        internal static string hyperLinkAddGuideRate {
            get {
                return ResourceManager.GetString("hyperLinkAddGuideRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Hotel.
        /// </summary>
        internal static string hyperLinkAddNewHotel {
            get {
                return ResourceManager.GetString("hyperLinkAddNewHotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Location.
        /// </summary>
        internal static string hyperLinkAddNewLocation {
            get {
                return ResourceManager.GetString("hyperLinkAddNewLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments admin.
        /// </summary>
        internal static string hyperLinkAdminComments {
            get {
                return ResourceManager.GetString("hyperLinkAdminComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin orders.
        /// </summary>
        internal static string hyperLinkAdminOrders {
            get {
                return ResourceManager.GetString("hyperLinkAdminOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency List.
        /// </summary>
        internal static string hyperLinkAgentList {
            get {
                return ResourceManager.GetString("hyperLinkAgentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat Administrator.
        /// </summary>
        internal static string hyperLinkBoatAdministrator {
            get {
                return ResourceManager.GetString("hyperLinkBoatAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories management.
        /// </summary>
        internal static string hyperLinkBoatCategories {
            get {
                return ResourceManager.GetString("hyperLinkBoatCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new boat.
        /// </summary>
        internal static string hyperLinkBoatEdit {
            get {
                return ResourceManager.GetString("hyperLinkBoatEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat List.
        /// </summary>
        internal static string hyperLinkBoatList {
            get {
                return ResourceManager.GetString("hyperLinkBoatList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Boat Management.
        /// </summary>
        internal static string hyperLinkBoatManagement {
            get {
                return ResourceManager.GetString("hyperLinkBoatManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room types configuration.
        /// </summary>
        internal static string hyperLinkBoatRoomTypes {
            get {
                return ResourceManager.GetString("hyperLinkBoatRoomTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add trip tour.
        /// </summary>
        internal static string hyperLinkBoatTripTourEdit {
            get {
                return ResourceManager.GetString("hyperLinkBoatTripTourEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip tour list.
        /// </summary>
        internal static string hyperLinkBoatTripTourList {
            get {
                return ResourceManager.GetString("hyperLinkBoatTripTourList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat types management.
        /// </summary>
        internal static string hyperLinkBoatTypes {
            get {
                return ResourceManager.GetString("hyperLinkBoatTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuisine Edit.
        /// </summary>
        internal static string hyperLinkCuisineEdit {
            get {
                return ResourceManager.GetString("hyperLinkCuisineEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrance Fee Types.
        /// </summary>
        internal static string hyperLinkEntranceFeeTypes {
            get {
                return ResourceManager.GetString("hyperLinkEntranceFeeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide Administrator.
        /// </summary>
        internal static string hyperLinkGuideAdministrator {
            get {
                return ResourceManager.GetString("hyperLinkGuideAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new guide.
        /// </summary>
        internal static string hyperLinkGuideEdit {
            get {
                return ResourceManager.GetString("hyperLinkGuideEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages setting.
        /// </summary>
        internal static string hyperLinkGuideLanguagesSetting {
            get {
                return ResourceManager.GetString("hyperLinkGuideLanguagesSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide List.
        /// </summary>
        internal static string hyperLinkGuideList {
            get {
                return ResourceManager.GetString("hyperLinkGuideList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide Management.
        /// </summary>
        internal static string hyperLinkGuideManagement {
            get {
                return ResourceManager.GetString("hyperLinkGuideManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide Rate.
        /// </summary>
        internal static string hyperLinkGuideRate {
            get {
                return ResourceManager.GetString("hyperLinkGuideRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide Services.
        /// </summary>
        internal static string hyperLinkGuideServices {
            get {
                return ResourceManager.GetString("hyperLinkGuideServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HyperLinkHomePage {
            get {
                return ResourceManager.GetString("HyperLinkHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel List.
        /// </summary>
        internal static string hyperLinkHotelList {
            get {
                return ResourceManager.GetString("hyperLinkHotelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator Administrator.
        /// </summary>
        internal static string hyperLinkHotelLogList {
            get {
                return ResourceManager.GetString("hyperLinkHotelLogList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Management.
        /// </summary>
        internal static string HyperLinkHotelManagement {
            get {
                return ResourceManager.GetString("HyperLinkHotelManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new destination.
        /// </summary>
        internal static string hyperLinkLandscapeEdit {
            get {
                return ResourceManager.GetString("hyperLinkLandscapeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination list.
        /// </summary>
        internal static string hyperLinkLandscapeList {
            get {
                return ResourceManager.GetString("hyperLinkLandscapeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination management.
        /// </summary>
        internal static string hyperLinkLandscapeManagement {
            get {
                return ResourceManager.GetString("hyperLinkLandscapeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location List.
        /// </summary>
        internal static string hyperLinkLocationList {
            get {
                return ResourceManager.GetString("hyperLinkLocationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Management.
        /// </summary>
        internal static string HyperLinkLocationManagement {
            get {
                return ResourceManager.GetString("HyperLinkLocationManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Typical dishes.
        /// </summary>
        internal static string hyperLinkMealEdit {
            get {
                return ResourceManager.GetString("hyperLinkMealEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typical dishes list.
        /// </summary>
        internal static string hyperLinkMealList {
            get {
                return ResourceManager.GetString("hyperLinkMealList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price list.
        /// </summary>
        internal static string hyperLinkPriceList {
            get {
                return ResourceManager.GetString("hyperLinkPriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing Management.
        /// </summary>
        internal static string HyperLinkPricingManagement {
            get {
                return ResourceManager.GetString("HyperLinkPricingManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Edit.
        /// </summary>
        internal static string hyperLinkProviderEdit {
            get {
                return ResourceManager.GetString("hyperLinkProviderEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider List.
        /// </summary>
        internal static string hyperLinkProviderList {
            get {
                return ResourceManager.GetString("hyperLinkProviderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin comments.
        /// </summary>
        internal static string hyperLinkRestaurantComments {
            get {
                return ResourceManager.GetString("hyperLinkRestaurantComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new restaurant.
        /// </summary>
        internal static string hyperLinkRestaurantEdit {
            get {
                return ResourceManager.GetString("hyperLinkRestaurantEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant List.
        /// </summary>
        internal static string hyperLinkRestaurantList {
            get {
                return ResourceManager.GetString("hyperLinkRestaurantList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Management.
        /// </summary>
        internal static string hyperLinkRestaurantManagement {
            get {
                return ResourceManager.GetString("hyperLinkRestaurantManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room types configurations.
        /// </summary>
        internal static string hyperLinkRoomTypes {
            get {
                return ResourceManager.GetString("hyperLinkRoomTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new route.
        /// </summary>
        internal static string hyperLinkRouteEdit {
            get {
                return ResourceManager.GetString("hyperLinkRouteEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route list.
        /// </summary>
        internal static string hyperLinkRouteList {
            get {
                return ResourceManager.GetString("hyperLinkRouteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new tour.
        /// </summary>
        internal static string hyperLinkTourEdit {
            get {
                return ResourceManager.GetString("hyperLinkTourEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tours management.
        /// </summary>
        internal static string hyperLinkTourList {
            get {
                return ResourceManager.GetString("hyperLinkTourList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour regions.
        /// </summary>
        internal static string hyperLinkTourRegions {
            get {
                return ResourceManager.GetString("hyperLinkTourRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour types.
        /// </summary>
        internal static string hyperLinkTourTypes {
            get {
                return ResourceManager.GetString("hyperLinkTourTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Transport.
        /// </summary>
        internal static string hyperLinkTransportEdit {
            get {
                return ResourceManager.GetString("hyperLinkTransportEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport List.
        /// </summary>
        internal static string hyperLinkTransportList {
            get {
                return ResourceManager.GetString("hyperLinkTransportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator Administrator.
        /// </summary>
        internal static string hyperLinkTransportLogList {
            get {
                return ResourceManager.GetString("hyperLinkTransportLogList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport Type Setting.
        /// </summary>
        internal static string hyperLinkTransportTypeSetting {
            get {
                return ResourceManager.GetString("hyperLinkTransportTypeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go in.
        /// </summary>
        internal static string ibnDown {
            get {
                return ResourceManager.GetString("ibnDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up one level.
        /// </summary>
        internal static string ibnUp {
            get {
                return ResourceManager.GetString("ibnUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abtract Image (150x115 recommened).
        /// </summary>
        internal static string LabelAbtractImage {
            get {
                return ResourceManager.GetString("LabelAbtractImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string labelAction {
            get {
                return ResourceManager.GetString("labelAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string labelActivities {
            get {
                return ResourceManager.GetString("labelActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string labelAddress {
            get {
                return ResourceManager.GetString("labelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency Pricing.
        /// </summary>
        internal static string labelAgencyPricing {
            get {
                return ResourceManager.GetString("labelAgencyPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string labelAuthor {
            get {
                return ResourceManager.GetString("labelAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account.
        /// </summary>
        internal static string labelAuthorAccount {
            get {
                return ResourceManager.GetString("labelAuthorAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End In.
        /// </summary>
        internal static string labelCityEnd {
            get {
                return ResourceManager.GetString("labelCityEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start From.
        /// </summary>
        internal static string labelCityStart {
            get {
                return ResourceManager.GetString("labelCityStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment management.
        /// </summary>
        internal static string labelCommentManagement {
            get {
                return ResourceManager.GetString("labelCommentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string labelContent {
            get {
                return ResourceManager.GetString("labelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Settings.
        /// </summary>
        internal static string labelCurrencies {
            get {
                return ResourceManager.GetString("labelCurrencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string labelDescription {
            get {
                return ResourceManager.GetString("labelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details Initerary.
        /// </summary>
        internal static string labelDetailsIniterary {
            get {
                return ResourceManager.GetString("labelDetailsIniterary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string labelEmail {
            get {
                return ResourceManager.GetString("labelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End at.
        /// </summary>
        internal static string labelEndIn {
            get {
                return ResourceManager.GetString("labelEndIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusion.
        /// </summary>
        internal static string labelExclusion {
            get {
                return ResourceManager.GetString("labelExclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string labelFax {
            get {
                return ResourceManager.GetString("labelFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured.
        /// </summary>
        internal static string labelFeatured {
            get {
                return ResourceManager.GetString("labelFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname.
        /// </summary>
        internal static string labelFullName {
            get {
                return ResourceManager.GetString("labelFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        internal static string labelGrade {
            get {
                return ResourceManager.GetString("labelGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Management.
        /// </summary>
        internal static string labelHotelManagement {
            get {
                return ResourceManager.GetString("labelHotelManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string labelImage {
            get {
                return ResourceManager.GetString("labelImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclusion.
        /// </summary>
        internal static string labelInclusion {
            get {
                return ResourceManager.GetString("labelInclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content contains.
        /// </summary>
        internal static string labelInContent {
            get {
                return ResourceManager.GetString("labelInContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string labelIP {
            get {
                return ResourceManager.GetString("labelIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string labelLocation {
            get {
                return ResourceManager.GetString("labelLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Edit.
        /// </summary>
        internal static string labelLocationEdit {
            get {
                return ResourceManager.GetString("labelLocationEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string labelMap {
            get {
                return ResourceManager.GetString("labelMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string labelMobile {
            get {
                return ResourceManager.GetString("labelMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Management.
        /// </summary>
        internal static string labelModuleManagement {
            get {
                return ResourceManager.GetString("labelModuleManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Currency.
        /// </summary>
        internal static string labelNewCurrency {
            get {
                return ResourceManager.GetString("labelNewCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tour region.
        /// </summary>
        internal static string labelNewTourRegion {
            get {
                return ResourceManager.GetString("labelNewTourRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tour type.
        /// </summary>
        internal static string labelNewTourType {
            get {
                return ResourceManager.GetString("labelNewTourType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note for Operator.
        /// </summary>
        internal static string labelNoteForOperator {
            get {
                return ResourceManager.GetString("labelNoteForOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note for Sale.
        /// </summary>
        internal static string labelNoteForSale {
            get {
                return ResourceManager.GetString("labelNoteForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of days.
        /// </summary>
        internal static string labelNumberOfDays {
            get {
                return ResourceManager.GetString("labelNumberOfDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order priority.
        /// </summary>
        internal static string labelOrderPriority {
            get {
                return ResourceManager.GetString("labelOrderPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent location.
        /// </summary>
        internal static string labelParent {
            get {
                return ResourceManager.GetString("labelParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location List.
        /// </summary>
        internal static string labelPositionList {
            get {
                return ResourceManager.GetString("labelPositionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted.
        /// </summary>
        internal static string labelPosted {
            get {
                return ResourceManager.GetString("labelPosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted by.
        /// </summary>
        internal static string labelPostedUser {
            get {
                return ResourceManager.GetString("labelPostedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point: {0}.
        /// </summary>
        internal static string labelProviderFeatured {
            get {
                return ResourceManager.GetString("labelProviderFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region name.
        /// </summary>
        internal static string labelRegionName {
            get {
                return ResourceManager.GetString("labelRegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered date.
        /// </summary>
        internal static string labelRegisteredTime {
            get {
                return ResourceManager.GetString("labelRegisteredTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role .
        /// </summary>
        internal static string labelRole {
            get {
                return ResourceManager.GetString("labelRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start at.
        /// </summary>
        internal static string labelStartAt {
            get {
                return ResourceManager.GetString("labelStartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        internal static string labelSummary {
            get {
                return ResourceManager.GetString("labelSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string labelTel {
            get {
                return ResourceManager.GetString("labelTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour.
        /// </summary>
        internal static string labelTour {
            get {
                return ResourceManager.GetString("labelTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour configuration.
        /// </summary>
        internal static string labelTourConfiguration {
            get {
                return ResourceManager.GetString("labelTourConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Information.
        /// </summary>
        internal static string labelTourEdit {
            get {
                return ResourceManager.GetString("labelTourEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Instruction.
        /// </summary>
        internal static string labelTourInstruction {
            get {
                return ResourceManager.GetString("labelTourInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tours Management.
        /// </summary>
        internal static string labelTourList {
            get {
                return ResourceManager.GetString("labelTourList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string labelTourRegion {
            get {
                return ResourceManager.GetString("labelTourRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour regions.
        /// </summary>
        internal static string labelTourRegions {
            get {
                return ResourceManager.GetString("labelTourRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Type.
        /// </summary>
        internal static string labelTourType {
            get {
                return ResourceManager.GetString("labelTourType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Type Information.
        /// </summary>
        internal static string labelTourTypeInformation {
            get {
                return ResourceManager.GetString("labelTourTypeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Type Management.
        /// </summary>
        internal static string labelTourTypeManagement {
            get {
                return ResourceManager.GetString("labelTourTypeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour type.
        /// </summary>
        internal static string labelTourTypeName {
            get {
                return ResourceManager.GetString("labelTourTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Highlight.
        /// </summary>
        internal static string labelTripHighLight {
            get {
                return ResourceManager.GetString("labelTripHighLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip length.
        /// </summary>
        internal static string labelTripLength {
            get {
                return ResourceManager.GetString("labelTripLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated successful.
        /// </summary>
        internal static string labelUpdateStatus {
            get {
                return ResourceManager.GetString("labelUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string labelUserName {
            get {
                return ResourceManager.GetString("labelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose Location.
        /// </summary>
        internal static string labelValidLocation {
            get {
                return ResourceManager.GetString("labelValidLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string labelWebsite {
            get {
                return ResourceManager.GetString("labelWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to take.
        /// </summary>
        internal static string labelWhatToTake {
            get {
                return ResourceManager.GetString("labelWhatToTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of users in role .
        /// </summary>
        internal static string lblListOfUserIn {
            get {
                return ResourceManager.GetString("lblListOfUserIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete this location?.
        /// </summary>
        internal static string messageConfirmDeleteLocation {
            get {
                return ResourceManager.GetString("messageConfirmDeleteLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: You may have input wrong data. Can not apply for the value between {0} and {1}. There is no range to apply..
        /// </summary>
        internal static string messageErrorDontHaveRangeFor {
            get {
                return ResourceManager.GetString("messageErrorDontHaveRangeFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: You may have input wrong data. Can not apply for the value between {1} and {0}. There is two range to apply..
        /// </summary>
        internal static string messageErrorOneValueBelongToTwoRange {
            get {
                return ResourceManager.GetString("messageErrorOneValueBelongToTwoRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: You may have input wrong data. There is two range without max value..
        /// </summary>
        internal static string messageErrorTwoMaxValue {
            get {
                return ResourceManager.GetString("messageErrorTwoMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Return to root level).
        /// </summary>
        internal static string messageGoBackToRoot {
            get {
                return ResourceManager.GetString("messageGoBackToRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Return to {0}).
        /// </summary>
        internal static string messageGoUpOneLevel {
            get {
                return ResourceManager.GetString("messageGoUpOneLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the list of location whose parent is {0}.
        /// </summary>
        internal static string messageLocationListParent {
            get {
                return ResourceManager.GetString("messageLocationListParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No location found at this..
        /// </summary>
        internal static string messageNotFoundAnyLocation {
            get {
                return ResourceManager.GetString("messageNotFoundAnyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted after.
        /// </summary>
        internal static string PostedAfter {
            get {
                return ResourceManager.GetString("PostedAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted before.
        /// </summary>
        internal static string PostedBefore {
            get {
                return ResourceManager.GetString("PostedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file type is not supported. Please contact Administrator..
        /// </summary>
        internal static string RevImage {
            get {
                return ResourceManager.GetString("RevImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required!.
        /// </summary>
        internal static string RfvName {
            get {
                return ResourceManager.GetString("RfvName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} result(s).
        /// </summary>
        internal static string stringFormatResult {
            get {
                return ResourceManager.GetString("stringFormatResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total users: {0}.
        /// </summary>
        internal static string stringFormatUserCount {
            get {
                return ResourceManager.GetString("stringFormatUserCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied: You don&apos;t have permission..
        /// </summary>
        internal static string textAccessDenied {
            get {
                return ResourceManager.GetString("textAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency Type/Role.
        /// </summary>
        internal static string textAgencyType {
            get {
                return ResourceManager.GetString("textAgencyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And go on.
        /// </summary>
        internal static string textAndUp {
            get {
                return ResourceManager.GetString("textAndUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply with.
        /// </summary>
        internal static string textApply {
            get {
                return ResourceManager.GetString("textApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string textCount {
            get {
                return ResourceManager.GetString("textCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string textFrom {
            get {
                return ResourceManager.GetString("textFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include .
        /// </summary>
        internal static string textInclude {
            get {
                return ResourceManager.GetString("textInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCESS DENIED: YOU DON&apos;T HAVE PERMISSION TO MODIFY THIS.
        /// </summary>
        internal static string textModifyDenied {
            get {
                return ResourceManager.GetString("textModifyDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Root --.
        /// </summary>
        internal static string textRoot {
            get {
                return ResourceManager.GetString("textRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string textTo {
            get {
                return ResourceManager.GetString("textTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  users.
        /// </summary>
        internal static string textUser {
            get {
                return ResourceManager.GetString("textUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This pricing table will be apply for {0}.
        /// </summary>
        internal static string titleAdminAgencyEdit {
            get {
                return ResourceManager.GetString("titleAdminAgencyEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of users in role {0}.
        /// </summary>
        internal static string titleAdminAgencyUserList {
            get {
                return ResourceManager.GetString("titleAdminAgencyUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency List.
        /// </summary>
        internal static string titleAdminAgentList {
            get {
                return ResourceManager.GetString("titleAdminAgentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Settings.
        /// </summary>
        internal static string titleAdminCurrencies {
            get {
                return ResourceManager.GetString("titleAdminCurrencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Location.
        /// </summary>
        internal static string titleAdminPositionEdit {
            get {
                return ResourceManager.GetString("titleAdminPositionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location List.
        /// </summary>
        internal static string titleAdminPositionList {
            get {
                return ResourceManager.GetString("titleAdminPositionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Provider.
        /// </summary>
        internal static string titleProviderEdit {
            get {
                return ResourceManager.GetString("titleProviderEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider List.
        /// </summary>
        internal static string titleProviderList {
            get {
                return ResourceManager.GetString("titleProviderList", resourceCulture);
            }
        }
    }
}
